import type { Metadata } from "next";
import Header from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import { getHeaderSession } from "@/components/sections/Header/_server/getHeaderSession";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headerSession = await getHeaderSession();
  console.log(
    `[layout_header_session] ${JSON.stringify({
      authenticated: headerSession.authenticated,
      hasLoginId: !!headerSession.loginId,
      hasUserId: headerSession.userId !== null,
      isPartner: headerSession.isPartner,
      isAdmin: headerSession.isAdmin,
    })}`,
  );

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@2.0/nanumsquare.css"
        />
      </head>
      <body>
        <Header
          authenticated={headerSession.authenticated}
          loginId={headerSession.loginId}
          isPartner={headerSession.isPartner}
          isAdmin={headerSession.isAdmin}
        />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
